name = "privara-intellectus"
type = "javascript"
main = "src/index.js"
compatibility_date = "2024-01-01"

[env.production]
name = "privara-intellectus-prod"

[[routes]]
pattern = "*.html"
zone_name = "pages.dev"

[build]
command = ""
cwd = "./"

[build.upload]
format = "service-worker"
